// creator
export const NEW_PROJECT = 'NEW_PROJECT';
export const LOAD_PROJECT = 'LOAD_PROJECT';
export const SET_ACTIVE_FRAME_ID = 'SET_ACTIVE_FRAME_ID';
export const ADD_FRAME = 'ADD_FRAME';
export const DELETE_FRAME = 'DELETE_FRAME';
export const DUPLICATE_FRAME = 'DUPLICATE_FRAME';
export const SET_FRAME_INTERVAL = 'SET_FRAME_INTERVAL';
export const SET_DURATION = 'SET_DURATION';
export const RESET_FRAME = 'RESET_FRAME';
export const APPEND_ROW = 'APPEND_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const APPEND_COL = 'APPEND_COL';
export const DELETE_COL = 'DELETE_COL';
export const SET_HOVERED_INDEX = 'SET_HOVERED_INDEX';
export const SELECT_PALETTE_COLOR = 'SELECT_PALETTE_COLOR';
export const CHANGE_PALETTE_COLOR = 'CHANGE_PALETTE_COLOR';
export const DRAW_WITH_PENCIL = 'DRAW_WITH_PENCIL';
export const DRAW_WITH_BUCKET = 'DRAW_WITH_BUCKET';
export const DRAW_WITH_ERASER = 'DRAW_WITH_ERASER';
export const DRAW_WITH_MOVE = 'DRAW_WITH_MOVE';
export const CHANGE_TOOL_TYPE = 'CHANGE_TOOL_TYPE';

// wallet
export const SWITCH_WALLET_MODAL = 'SWITCH_WALLET_MODAL';
export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST';
export const SET_ACCOUNT_ADDRESS = 'SET_ACCOUNT_ADDRESS';

// root
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';